### ISSUE TITLE
Document background color will not change

### ISSUE THREAD

**Issue by mud-ali** [waymondrang/docsafterdark#30]
despite using the given settings, the document page background color is remaining black

![image](https://user-images.githubusercontent.com/96320211/224849817-66227337-1bba-49eb-9f50-9fc5e57a897d.png)

![image](https://user-images.githubusercontent.com/96320211/224849862-df2dcca0-6779-4b09-8423-48b5db55ac6a.png)

**Comment by waymondrang** [comment]
Thank you for opening an issue. This behavior is not intended and has been fixed in the latest version 0.6.1. Please reopen this issue if the background page problem still persists.

**Comment by dc03** [comment]
> Thank you for opening an issue. This behavior is not intended and has been fixed in the latest version 0.6.1. Please reopen this issue if the background page problem still persists.

Still doesn't seem to be working for me...

![image](https://user-images.githubusercontent.com/44582521/225004679-ba2c9d2c-4745-4fd6-83b2-0647326861a3.png)

**Comment by dc03** [comment]
Okay, it seems to be because the class `.kix-appview-editor` seems to be having the CSS as
```css
.docs-grille-gm3 .kix-appview-editor, body.docs-grille-gm3, .docs-grille-gm3.docs-body-pageless .docs-horizontal-ruler, .docs-grille-gm3.docs-body-pageless .docs-ruler-background-inner, .docs-grille-gm3.docs-body-pageless .docs-vertical-ruler {
  background-color: var(--primary-background-color) !important;
}
```
whereas I think instead it should be
```css
.docs-grille-gm3 .kix-appview-editor, body.docs-grille-gm3, .docs-grille-gm3.docs-body-pageless .docs-horizontal-ruler, .docs-grille-gm3.docs-body-pageless .docs-ruler-background-inner, .docs-grille-gm3.docs-body-pageless .docs-vertical-ruler {
  background-color: var(--background-color) !important;
}
```
when inspecting the element
```
html body.docs-gm.docs-grille.docs-grille-gm3 div#docs-editor-container div#docs-editor div#kix-appview.kix-appview div.kix-appview-editor-container div.kix-appview-editor
```

I am on firefox 110.0.1 (64-bit)
